
all:
	git clone git://github.com/iBotPeaches/Apktool.git
	cd Apktool; ./gradlew; ./gradlew build fatJar;
	git clone git@github.com:matthewAURA/aurasium.git

clean:
	rm -rf Apktool/
	rm -rf aurasium/
